Documentation of source code
HibiscusMC/HMCCosmetics pull request #81
Opened 2023-03-14 19:50 UTC by Craftinators

The purpose of this PR is to document all/most of the source code inside this repo

2023-03-14 19:51 UTC, Craftinators commented
@LoJoSho 🚨 DON'T MERGE NOT READY 🚨

2023-03-14 22:32 UTC, LoJoSho commented
Looks good to me so far.

2023-03-15 08:09 UTC, Craftinators commented
To avoid a massive PR with undeniable merge conflicts, I think it's best to break it apart into directories. @LoJoSho double check all docs are correctly describing their methods 💯

2023-03-15 08:40 UTC, Craftinators reviewed
Should all of these be `Cancellable`?

2023-03-15 14:12 UTC, LoJoSho commented
No, certain events should not be cancellable.

2023-03-15 14:46 UTC, Craftinators commented
> No, certain events should not be cancellable.

Well currently all the events you made are cancellable, which I feel like, for example, PlayerMenuClose shouldn’t be cancellable

2023-03-15 15:11 UTC, LoJoSho commented
> > No, certain events should not be cancellable.
> 
> Well currently all the events you made are cancellable, which I feel like, for example, PlayerMenuClose shouldn’t be cancellable

There are certain events that implement cancellable, but canceling them doesn't actually do anything. That's most likely a leftover from when I was copying and pasting classes.

2023-03-15 15:22 UTC, Craftinators commented
> There are certain events that implement cancellable, but canceling them doesn't actually do anything. That's most likely a leftover from when I was copying and pasting classes.

And these would be what?

2023-03-15 20:17 UTC, LoJoSho requested changes

2023-03-15 20:17 UTC, LoJoSho commented on common/src/main/java/com/hibiscusmc/hmccosmetics/api/HMCCosmeticSetupEvent.java
> + * Called when the plugin is enabled
This is wrong, this happened whenever the plugin is setup/reloaded.

2023-03-16 01:17 UTC, LoJoSho approved these changes

2023-03-16 19:22 UTC, merged